typography_spectrum: 0.8680550344288349
color:
  brandColors:
    - '#f7f7f7'
    - '#020202'
    - '#363636'
    - '#ca0a15'
    - '#a0a0a0'
  brandStrength: 0.6875
  lightness: 0.4375
  saturation: 0.45934317051433027
  rhythmicContrast: 0.5
opengraph:
  image: null
  type: null
  appId: null
layout_spectrum: 0.96945
analytics:
  google: null
  facebook: null
  twitter: null
name: samuelmarks
cta:
  domain: null
  bucket: null
  version: null
navigation:
  - name: BUY/LISTEN
    url: samuelmarks.bandcamp.com
    type: external
favicon: null
title: Samuel Marks
description: Love Is Won
purpose: []
